#![cfg(all(
    feature = "cmd_midpoints",
    feature = "cmd_ends",
    feature = "cmd_lengths"
))]

//! Downstream compatibility checks for the public Rust output loaders.
//!
//! These tests load the cfDNAlab-generated downstream fixtures through
//! `cfdnalab::output_loaders`, rather than by reopening the raw TSV or Zarr
//! arrays directly. They are ignored because they require the fixture-generation
//! tests to run first. The downstream GitHub Action runs them after generating
//! fixtures and before the Python/R downstream checks consume the same files.
//! The expected values intentionally mirror the core metadata, full-array, and
//! selector expectations in `downstream_tests/python/*_cfdnalab_package.py`.

use anyhow::{Context, Result, ensure};
use cfdnalab::{
    interval::Interval,
    output_loaders::{
        EndMotifAxisKind, EndMotifRowMetadata, EndMotifRowMode, EndMotifStorageMode,
        LengthOutputMode, LengthRowMetadata, load_ends_output, load_lengths_output,
        load_midpoints_output,
    },
};
use std::{
    env,
    path::{Path, PathBuf},
};

const FIXTURE_DIR: &str = "downstream_tests/tmp";
const EXPECTED_MIDPOINT_COUNTS_ROW_MAJOR: &[f32] = &[
    1.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.5, 1.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 1.5, 0.0, 0.5, 0.0, 0.5, 0.0, 1.0, 0.0, 0.0, 0.0, 2.5, 0.0, 0.0, 0.5, 0.0, 0.0,
    1.5, 0.0, 0.0, 0.0, 0.5, 0.0, 1.0,
];
const EXPECTED_MIDPOINT_GROUPS: &[(usize, &str, u64)] =
    &[(0, "LYL1", 2), (1, "beta-site", 2), (2, "gamma_long", 2)];
const EXPECTED_LENGTH_BINS: &[(u32, u32, usize)] = &[(30, 50, 0), (50, 70, 1), (70, 100, 2)];
const EXPECTED_LENGTH_COUNTS_GLOBAL: &[f64] = &[3.0, 2.0, 1.0];
const EXPECTED_LENGTH_COUNTS_WINDOWED: &[f64] =
    &[2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0];
const EXPECTED_LENGTH_COUNTS_GROUPED: &[f64] =
    &[2.0, 0.0, 1.0, 0.0, 2.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0];

/// Verify the Rust midpoint loader against generated downstream fixtures.
#[test]
#[ignore = "requires downstream fixtures generated by cfDNAlab"]
fn rust_midpoint_loader_reads_downstream_fixture() -> Result<()> {
    let midpoints = load_midpoints_output(fixture_dir_path(
        "CFDNALAB_MIDPOINT_ZARR",
        "tiny.midpoint_profiles.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(midpoints.counts_shape(), (3, 3, 5));
    assert_eq!(
        midpoints
            .group_metadata()
            .iter()
            .map(|group| (group.index, group.name.as_str(), group.eligible_intervals))
            .collect::<Vec<_>>(),
        EXPECTED_MIDPOINT_GROUPS
    );
    assert_eq!(
        midpoints
            .length_bins()
            .iter()
            .map(|bin| bin.as_tuple())
            .collect::<Vec<_>>(),
        EXPECTED_LENGTH_BINS
    );
    assert_eq!(
        midpoints
            .position_bins()
            .iter()
            .map(|bin| bin.as_tuple())
            .collect::<Vec<_>>(),
        vec![(0, 2, 0), (2, 4, 1), (4, 6, 2), (6, 8, 3), (8, 10, 4)]
    );
    assert_eq!(midpoints.group_index("beta-site")?, 1);
    assert_eq!(midpoints.length_bin_for_length(49), Some(0));
    assert_eq!(midpoints.length_bin_for_length(50), Some(1));
    assert_eq!(midpoints.length_bin_for_length(70), Some(2));

    let all_counts = midpoints.read_all_counts()?;
    assert_eq!(all_counts.shape(), (3, 3, 5));
    assert_f32_slice_near(
        all_counts.counts_row_major(),
        EXPECTED_MIDPOINT_COUNTS_ROW_MAJOR,
    );

    let selected_by_index = midpoints.select().groups(&[1]).length_bins(&[1]).read()?;
    assert_eq!(selected_by_index.shape(), (1, 1, 5));
    assert_f32_slice_near(
        selected_by_index.counts_row_major(),
        &[0.0, 0.0, 1.5, 0.0, 0.5],
    );

    let selected_by_group_name = midpoints.select().groups_by_name(&["LYL1"]).read()?;
    assert_eq!(selected_by_group_name.shape(), (1, 3, 5));
    assert_f32_slice_near(
        selected_by_group_name.counts_row_major(),
        &EXPECTED_MIDPOINT_COUNTS_ROW_MAJOR[0..15],
    );

    let selected_by_length = midpoints.select().length_bins(&[2]).read()?;
    assert_eq!(selected_by_length.shape(), (3, 1, 5));
    assert_f32_slice_near(
        selected_by_length.counts_row_major(),
        &[
            0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.5, 0.0, 1.0, 0.0, 0.0, 0.0, 0.5, 0.0, 1.0,
        ],
    );

    let selected_by_group_and_range = midpoints
        .select()
        .groups_by_name(&["gamma_long", "LYL1"])
        .length_range(Interval::new(50, 100)?)
        .read()?;
    assert_eq!(selected_by_group_and_range.shape(), (2, 2, 5));
    assert_eq!(selected_by_group_and_range.group_indices(), &[2, 0]);
    assert_eq!(
        selected_by_group_and_range
            .length_bins()
            .iter()
            .map(|bin| bin.as_tuple())
            .collect::<Vec<_>>(),
        vec![(50, 70, 1), (70, 100, 2)]
    );
    assert_f32_slice_near(
        selected_by_group_and_range.counts_row_major(),
        &[
            0.5, 0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 0.5, 0.0, 1.0, 0.0, 0.0, 1.5, 0.5, 0.0, 0.0, 0.0,
            0.0, 0.0, 2.0,
        ],
    );
    assert_eq!(
        selected_by_group_and_range
            .groups()
            .iter()
            .map(|group| group.name.as_str())
            .collect::<Vec<_>>(),
        vec!["gamma_long", "LYL1"]
    );
    let mut profile_summaries = Vec::new();
    for (selected_group_index, group) in selected_by_group_and_range.groups().iter().enumerate() {
        for (selected_length_index, length_bin) in selected_by_group_and_range
            .length_bins()
            .iter()
            .enumerate()
        {
            let profile = selected_by_group_and_range
                .profile(selected_group_index, selected_length_index)
                .expect("selected profile indices should be in bounds");
            profile_summaries.push((
                group.name.as_str(),
                length_bin.as_tuple(),
                profile.iter().copied().sum::<f32>(),
            ));
        }
    }
    assert_eq!(
        profile_summaries
            .iter()
            .map(|(group_name, length_bin, _)| (*group_name, *length_bin))
            .collect::<Vec<_>>(),
        vec![
            ("gamma_long", (50, 70, 1)),
            ("gamma_long", (70, 100, 2)),
            ("LYL1", (50, 70, 1)),
            ("LYL1", (70, 100, 2)),
        ]
    );
    assert_f32_slice_near(
        profile_summaries
            .iter()
            .map(|(_, _, profile_total)| *profile_total)
            .collect::<Vec<_>>()
            .as_slice(),
        &[2.0, 1.5, 2.0, 2.0],
    );

    Ok(())
}

/// Verify Rust end-motif loader behavior across downstream end-motif fixtures.
#[test]
#[ignore = "requires downstream fixtures generated by cfDNAlab"]
fn rust_end_motif_loader_reads_downstream_fixtures() -> Result<()> {
    check_dense_global_end_motifs()?;
    check_sparse_windowed_end_motifs()?;
    check_sparse_windowed_selected_motifs()?;
    check_sparse_grouped_end_motifs()?;
    check_sparse_grouped_motif_groups()?;
    check_sparse_grouped_wide_motif_groups()?;

    Ok(())
}

/// Verify Rust lengths loader behavior across downstream lengths fixtures.
#[test]
#[ignore = "requires downstream fixtures generated by cfDNAlab"]
fn rust_lengths_loader_reads_downstream_fixtures() -> Result<()> {
    check_global_lengths()?;
    check_windowed_lengths(
        "CFDNALAB_LENGTHS_WINDOWED_TSV",
        "tiny_lengths_windowed.length_counts.tsv.zst",
        true,
    )?;
    check_windowed_lengths(
        "CFDNALAB_LENGTHS_WINDOWED_NO_BLACKLIST_TSV",
        "tiny_lengths_windowed_no_blacklist.length_counts.tsv.zst",
        false,
    )?;
    check_grouped_lengths(
        "CFDNALAB_LENGTHS_GROUPED_TSV",
        "tiny_lengths_grouped.length_counts.tsv.zst",
        true,
    )?;
    check_grouped_lengths(
        "CFDNALAB_LENGTHS_GROUPED_NO_BLACKLIST_TSV",
        "tiny_lengths_grouped_no_blacklist.length_counts.tsv.zst",
        false,
    )?;

    Ok(())
}

/// Check the dense global end-motif downstream fixture.
fn check_dense_global_end_motifs() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_DENSE_GLOBAL_ZARR",
        "tiny_dense_global.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::Dense);
    assert_eq!(ends.row_mode(), EndMotifRowMode::Global);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::Motif);
    assert_eq!(ends.motif_labels(), &["_A", "_C", "_G", "_T"]);
    assert_eq!(ends.motif_index("_G")?, 2);
    assert_f64_slice_near(
        ends.dense_counts()?.values_row_major(),
        &[1.0, 0.0, 1.0, 0.0],
    );

    let selected = ends.select().motifs_by_label(&["_G", "_A"]).read()?;
    assert_eq!(selected.row_metadata(), &EndMotifRowMetadata::Global);
    assert!(selected.window_metadata().is_err());
    assert!(selected.group_metadata().is_err());
    assert_eq!(selected.shape(), (1, 2));
    assert_eq!(selected.motif_labels(), &["_G", "_A"]);
    assert_f64_slice_near(selected.dense_counts()?.values_row_major(), &[1.0, 1.0]);

    Ok(())
}

/// Check the sparse windowed end-motif downstream fixture.
fn check_sparse_windowed_end_motifs() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_SPARSE_WINDOWED_ZARR",
        "tiny_sparse_windowed.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::SparseCoo);
    assert_eq!(ends.row_mode(), EndMotifRowMode::BedWindows);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::Motif);
    assert_eq!(ends.motif_labels(), &["_A", "_G"]);
    assert_eq!(ends.sparse_counts()?.nnz(), 3);
    assert_f64_slice_near(
        ends.sparse_counts()?.to_dense_matrix()?.values_row_major(),
        &[0.0, 1.0, 1.0, 0.0, 0.0, 1.0],
    );
    assert_f64_slice_near(
        ends.select()
            .windows(&[1])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[1.0, 0.0],
    );
    assert_f64_slice_near(
        ends.select()
            .motifs_by_label(&["_G"])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[1.0, 0.0, 1.0],
    );

    let windows = ends.window_metadata()?;
    assert_eq!(
        windows
            .iter()
            .map(|window| (
                window.index,
                window.chrom.as_str(),
                window.interval.as_tuple()
            ))
            .collect::<Vec<_>>(),
        vec![
            (0, "chr1", (10, 11)),
            (1, "chr1", (19, 20)),
            (2, "chr2", (10, 11))
        ]
    );
    assert!(
        windows
            .iter()
            .all(|window| window.blacklisted_fraction == Some(0.0))
    );

    let selected = ends
        .select()
        .windows(&[1, 0])
        .motifs_by_label(&["_G", "_A"])
        .read()?;
    assert_eq!(selected.shape(), (2, 2));
    assert_eq!(selected.row_indices(), &[1, 0]);
    assert_eq!(selected.motif_labels(), &["_G", "_A"]);
    assert_eq!(
        selected
            .window_metadata()?
            .iter()
            .map(|window| (
                window.index,
                window.chrom.as_str(),
                window.interval.as_tuple()
            ))
            .collect::<Vec<_>>(),
        vec![(1, "chr1", (19, 20)), (0, "chr1", (10, 11))]
    );
    assert_f64_slice_near(
        selected.to_dense_matrix()?.values_row_major(),
        &[0.0, 1.0, 1.0, 0.0],
    );

    Ok(())
}

/// Check sparse windowed end motifs with a selected motif set.
fn check_sparse_windowed_selected_motifs() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_SPARSE_WINDOWED_SELECTED_MOTIFS_ZARR",
        "tiny_sparse_windowed_selected_motifs.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::SparseCoo);
    assert_eq!(ends.row_mode(), EndMotifRowMode::BedWindows);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::Motif);
    assert_eq!(ends.motif_labels(), &["GT_AC", "AC_GT"]);
    assert!(!ends.has_motif("TT_TT"));
    assert!(ends.motif_index("TT_TT").is_err());
    assert_f64_slice_near(
        ends.sparse_counts()?.to_dense_matrix()?.values_row_major(),
        &[0.0, 1.0, 1.0, 0.0, 0.0, 1.0],
    );

    let selected = ends.select().motifs_by_label(&["AC_GT", "GT_AC"]).read()?;
    assert_f64_slice_near(
        selected.to_dense_matrix()?.values_row_major(),
        &[1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
    );

    Ok(())
}

/// Check the sparse grouped end-motif downstream fixture.
fn check_sparse_grouped_end_motifs() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_SPARSE_GROUPED_ZARR",
        "tiny_sparse_grouped.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::SparseCoo);
    assert_eq!(ends.row_mode(), EndMotifRowMode::Groups);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::Motif);
    assert_eq!(ends.motif_labels(), &["_A", "_G"]);
    assert_eq!(ends.group_index("alpha")?, 1);
    assert_f64_slice_near(
        ends.sparse_counts()?.to_dense_matrix()?.values_row_major(),
        &[1.0, 2.0, 1.0, 0.0, 0.0, 0.0],
    );
    assert_eq!(
        ends.group_metadata()?
            .iter()
            .map(|group| (
                group.index,
                group.name.as_str(),
                group.eligible_windows,
                group.blacklisted_fraction,
            ))
            .collect::<Vec<_>>(),
        vec![
            (0, "beta", 2, 0.0),
            (1, "alpha", 1, 0.0),
            (2, "gamma", 1, 0.0)
        ]
    );
    assert_f64_slice_near(
        ends.select()
            .groups_by_name(&["beta"])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[1.0, 2.0],
    );
    assert_f64_slice_near(
        ends.select()
            .motifs_by_label(&["_A"])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[1.0, 1.0, 0.0],
    );

    let selected = ends
        .select()
        .groups_by_name(&["alpha", "beta"])
        .motifs_by_label(&["_G", "_A"])
        .read()?;
    assert_eq!(selected.row_indices(), &[1, 0]);
    assert_eq!(
        selected
            .group_metadata()?
            .iter()
            .map(|group| group.name.as_str())
            .collect::<Vec<_>>(),
        vec!["alpha", "beta"]
    );
    assert_f64_slice_near(
        selected.to_dense_matrix()?.values_row_major(),
        &[0.0, 1.0, 2.0, 1.0],
    );
    let selected_dense_counts = selected.to_dense_matrix()?;
    assert_eq!(
        selected
            .group_metadata()?
            .iter()
            .zip(selected_dense_counts.rows())
            .map(|(group, motif_counts)| {
                (
                    group.name.as_str(),
                    motif_counts.iter().copied().sum::<f64>(),
                )
            })
            .collect::<Vec<_>>(),
        vec![("alpha", 1.0), ("beta", 3.0)]
    );
    let alpha = ends.select().groups_by_name(&["alpha"]).read()?;
    assert_f64_slice_near(alpha.to_dense_matrix()?.values_row_major(), &[1.0, 0.0]);
    let gamma = ends.select().groups_by_name(&["gamma"]).read()?;
    assert_f64_slice_near(gamma.to_dense_matrix()?.values_row_major(), &[0.0, 0.0]);

    Ok(())
}

/// Check the sparse grouped motif-group downstream fixture.
fn check_sparse_grouped_motif_groups() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_SPARSE_GROUPED_MOTIF_GROUP_ZARR",
        "tiny_sparse_grouped_motif_groups.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::SparseCoo);
    assert_eq!(ends.row_mode(), EndMotifRowMode::Groups);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::MotifGroup);
    assert_eq!(ends.motif_labels(), &["left-hit", "right-hit"]);
    assert_eq!(ends.motif_index("right-hit")?, 1);
    assert!(ends.has_motif("left-hit"));
    assert!(!ends.has_motif("_A"));
    assert_f64_slice_near(
        ends.sparse_counts()?.to_dense_matrix()?.values_row_major(),
        &[2.0, 1.0, 0.0, 1.0, 0.0, 0.0],
    );

    let selected = ends
        .select()
        .groups_by_name(&["alpha", "beta"])
        .motifs_by_label(&["right-hit", "left-hit"])
        .read()?;
    assert_f64_slice_near(
        selected.to_dense_matrix()?.values_row_major(),
        &[1.0, 0.0, 1.0, 2.0],
    );
    let alpha = ends.select().groups_by_name(&["alpha"]).read()?;
    assert_f64_slice_near(alpha.to_dense_matrix()?.values_row_major(), &[0.0, 1.0]);
    let gamma = ends.select().groups_by_name(&["gamma"]).read()?;
    assert_f64_slice_near(gamma.to_dense_matrix()?.values_row_major(), &[0.0, 0.0]);

    Ok(())
}

/// Check the sparse grouped wide-motif-group downstream fixture.
fn check_sparse_grouped_wide_motif_groups() -> Result<()> {
    let ends = load_ends_output(fixture_dir_path(
        "CFDNALAB_ENDS_SPARSE_GROUPED_WIDE_MOTIF_GROUP_ZARR",
        "tiny_sparse_grouped_wide_motif_groups.end_motifs.zarr",
        FixtureKind::Directory,
    )?)?;

    assert_eq!(ends.storage_mode(), EndMotifStorageMode::SparseCoo);
    assert_eq!(ends.row_mode(), EndMotifRowMode::Groups);
    assert_eq!(ends.motif_axis_kind(), EndMotifAxisKind::MotifGroup);
    assert_eq!(ends.motif_labels(), &["right-hit-wide", "left-hit-wide"]);
    assert_eq!(ends.motif_index("left-hit-wide")?, 1);
    assert_f64_slice_near(
        ends.sparse_counts()?.to_dense_matrix()?.values_row_major(),
        &[1.0, 2.0, 1.0, 0.0, 0.0, 0.0],
    );
    assert_f64_slice_near(
        ends.select()
            .groups_by_name(&["alpha", "beta"])
            .motifs_by_label(&["left-hit-wide", "right-hit-wide"])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[0.0, 1.0, 2.0, 1.0],
    );
    assert_f64_slice_near(
        ends.select()
            .groups_by_name(&["beta"])
            .read()?
            .to_dense_matrix()?
            .values_row_major(),
        &[1.0, 2.0],
    );
    assert!(ends.motif_index("GT_AC").is_err());

    Ok(())
}

/// Check the global lengths downstream fixture.
fn check_global_lengths() -> Result<()> {
    let lengths = load_lengths_output(fixture_dir_path(
        "CFDNALAB_LENGTHS_GLOBAL_TSV",
        "tiny_lengths_global.length_counts.tsv.zst",
        FixtureKind::File,
    )?)?;

    assert_eq!(lengths.row_mode(), LengthOutputMode::Global);
    assert_eq!(
        lengths
            .length_bins()
            .iter()
            .map(|bin| bin.as_tuple())
            .collect::<Vec<_>>(),
        EXPECTED_LENGTH_BINS
    );
    assert_f64_slice_near(lengths.counts_row_major(), EXPECTED_LENGTH_COUNTS_GLOBAL);
    assert_eq!(lengths.length_bin_for_length(50), Some(1));

    let selected = lengths
        .select()
        .length_range(Interval::new(50, 100)?)
        .read()?;
    assert_eq!(selected.row_metadata(), &LengthRowMetadata::Global);
    assert_eq!(selected.shape(), (1, 2));
    assert_f64_slice_near(selected.counts_row_major(), &[2.0, 1.0]);

    Ok(())
}

/// Check one windowed lengths downstream fixture.
fn check_windowed_lengths(env_var: &str, default_name: &str, has_blacklist: bool) -> Result<()> {
    let lengths = load_lengths_output(fixture_dir_path(env_var, default_name, FixtureKind::File)?)?;

    assert_eq!(lengths.row_mode(), LengthOutputMode::Windows);
    assert_f64_slice_near(lengths.counts_row_major(), EXPECTED_LENGTH_COUNTS_WINDOWED);
    let windows = lengths.window_metadata()?;
    assert_eq!(
        windows
            .iter()
            .map(|window| (
                window.index,
                window.chrom.as_str(),
                window.interval.as_tuple()
            ))
            .collect::<Vec<_>>(),
        vec![
            (0, "chr1", (0, 100)),
            (1, "chr1", (100, 200)),
            (2, "chr1", (200, 300)),
            (3, "chr1", (300, 360)),
        ]
    );
    let expected_blacklist = has_blacklist.then_some([0.04, 0.05, 0.1, 0.25]);
    assert_optional_f64_values(
        windows
            .iter()
            .map(|window| window.blacklisted_fraction)
            .collect::<Vec<_>>()
            .as_slice(),
        expected_blacklist.as_ref().map(|values| values.as_slice()),
    );
    assert_f64_slice_near(
        lengths.select().windows(&[3]).read()?.counts_row_major(),
        &[1.0, 0.0, 0.0],
    );

    let selected = lengths
        .select()
        .windows(&[1, 3])
        .length_range(Interval::new(50, 100)?)
        .read()?;
    assert_eq!(selected.row_indices(), &[1, 3]);
    assert_eq!(selected.shape(), (2, 2));
    assert_eq!(
        selected
            .window_metadata()?
            .iter()
            .map(|window| (
                window.index,
                window.chrom.as_str(),
                window.interval.as_tuple()
            ))
            .collect::<Vec<_>>(),
        vec![(1, "chr1", (100, 200)), (3, "chr1", (300, 360))]
    );
    assert_f64_slice_near(selected.counts_row_major(), &[2.0, 0.0, 0.0, 0.0]);

    Ok(())
}

/// Check one grouped lengths downstream fixture.
fn check_grouped_lengths(env_var: &str, default_name: &str, has_blacklist: bool) -> Result<()> {
    let lengths = load_lengths_output(fixture_dir_path(env_var, default_name, FixtureKind::File)?)?;

    assert_eq!(lengths.row_mode(), LengthOutputMode::Groups);
    assert_eq!(lengths.group_index("gamma")?, 2);
    assert_f64_slice_near(lengths.counts_row_major(), EXPECTED_LENGTH_COUNTS_GROUPED);
    let groups = lengths.group_metadata()?;
    assert_eq!(
        groups
            .iter()
            .map(|group| (group.index, group.name.as_str(), group.eligible_windows))
            .collect::<Vec<_>>(),
        vec![
            (0, "beta", 2),
            (1, "alpha", 1),
            (2, "gamma", 1),
            (3, "zero", 1)
        ]
    );
    let expected_blacklist = has_blacklist.then_some([0.07, 0.05, 0.25, 0.333]);
    assert_optional_f64_values(
        groups
            .iter()
            .map(|group| group.blacklisted_fraction)
            .collect::<Vec<_>>()
            .as_slice(),
        expected_blacklist.as_ref().map(|values| values.as_slice()),
    );
    assert_f64_slice_near(
        lengths
            .select()
            .groups_by_name(&["beta"])
            .read()?
            .counts_row_major(),
        &[2.0, 0.0, 1.0],
    );

    let selected = lengths
        .select()
        .groups_by_name(&["beta", "zero"])
        .length_range(Interval::new(50, 100)?)
        .read()?;
    assert_eq!(selected.row_indices(), &[0, 3]);
    assert_eq!(selected.shape(), (2, 2));
    assert_f64_slice_near(selected.counts_row_major(), &[0.0, 1.0, 0.0, 0.0]);
    assert_eq!(
        selected
            .group_metadata()?
            .iter()
            .zip(selected.counts().rows())
            .map(|(group, length_counts)| {
                (
                    group.name.as_str(),
                    length_counts.iter().copied().sum::<f64>(),
                )
            })
            .collect::<Vec<_>>(),
        vec![("beta", 1.0), ("zero", 0.0)]
    );

    Ok(())
}

#[derive(Debug, Clone, Copy)]
enum FixtureKind {
    Directory,
    File,
}

/// Resolve and validate a downstream fixture path.
fn fixture_dir_path(env_var: &str, default_name: &str, kind: FixtureKind) -> Result<PathBuf> {
    let path = env::var_os(env_var)
        .map(PathBuf::from)
        .unwrap_or_else(|| Path::new(FIXTURE_DIR).join(default_name));
    match kind {
        FixtureKind::Directory => ensure!(
            path.is_dir(),
            "{env_var} fixture directory does not exist at {}. Generate downstream fixtures first.",
            path.display()
        ),
        FixtureKind::File => ensure!(
            path.is_file(),
            "{env_var} fixture file does not exist at {}. Generate downstream fixtures first.",
            path.display()
        ),
    }
    Ok(path)
}

/// Assert two `f32` slices are equal within test tolerance.
fn assert_f32_slice_near(actual: &[f32], expected: &[f32]) {
    assert_eq!(actual.len(), expected.len(), "slice lengths differ");
    for (index, (&actual_value, &expected_value)) in actual.iter().zip(expected).enumerate() {
        assert!(
            (actual_value - expected_value).abs() <= 1e-6,
            "value {index} differs: actual {actual_value}, expected {expected_value}"
        );
    }
}

/// Assert two `f64` slices are equal within test tolerance.
fn assert_f64_slice_near(actual: &[f64], expected: &[f64]) {
    assert_eq!(actual.len(), expected.len(), "slice lengths differ");
    for (index, (&actual_value, &expected_value)) in actual.iter().zip(expected).enumerate() {
        assert!(
            (actual_value - expected_value).abs() <= 1e-9,
            "value {index} differs: actual {actual_value}, expected {expected_value}"
        );
    }
}

/// Assert optional blacklist fractions match expected presence and values.
fn assert_optional_f64_values(actual: &[Option<f64>], expected: Option<&[f64]>) {
    match expected {
        Some(expected_values) => {
            assert_eq!(
                actual.len(),
                expected_values.len(),
                "optional slice lengths differ"
            );
            for (index, (actual_value, &expected_value)) in
                actual.iter().zip(expected_values).enumerate()
            {
                let actual_value =
                    actual_value.with_context(|| format!("value {index} was missing"));
                let actual_value = actual_value.expect("expected a blacklisted_fraction value");
                assert!(
                    (actual_value - expected_value).abs() <= 1e-9,
                    "value {index} differs: actual {actual_value}, expected {expected_value}"
                );
            }
        }
        None => assert!(
            actual.iter().all(Option::is_none),
            "expected all blacklisted_fraction values to be absent"
        ),
    }
}
