/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Get Started',
      items: ['get-started/installation', 'get-started/quickstart']
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [{ type: 'autogenerated', dirName: 'generated/cli' }]
    },
    'release-notes'
  ]
};

module.exports = sidebars;
