/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Get Started',
      items: ['get-started/installation', 'get-started/quickstart']
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/gc-bias-pipeline',
        'guides/genomic-smoothing-pipeline',
        'guides/fcoverage-recipes',
        'guides/lengths-recipes',
        'guides/midpoints-recipes'
      ]
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [{ type: 'autogenerated', dirName: 'generated/cli' }]
    },
    'generated/release-notes'
  ]
};

module.exports = sidebars;
