/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Get Started',
      items: [
        'get-started/installation',
        'get-started/common-files',
      ]
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/correct_gc_bias_guide',
        'guides/genomic_smoothing_guide',
        'guides/fragment_coverage_guide',
        'guides/fragment_lengths_guide',
        'guides/fragment_midpoints_guide'
      ]
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [{ type: 'autogenerated', dirName: 'generated/cli' }]
    },
    'generated/release-notes'
  ]
};

module.exports = sidebars;
