pub(crate) mod config;
pub(crate) mod counting_by_group;
pub(crate) mod group_index;
pub(crate) mod midpoints;
#[cfg(feature = "plotters")]
pub(crate) mod plotting;
pub(crate) mod postprocess;
pub(crate) mod settings;
pub(crate) mod smoothing;
pub(crate) mod strand;
pub(crate) mod windows;
pub(crate) mod zarr;
